# Nginx tabanlı bir Docker imajı kullanılıyor
FROM nginx:latest

# Yerel dosyaları nginx'in web sunucusu kök dizinine kopyalayın
COPY . /usr/share/nginx/html

# Nginx web sunucusu 80 portunu expose eder
EXPOSE 80