---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-argocd-ingress
  annotations:
      ingressClassName: traefik   # NGINX yerine Traefik kullanıyoruz
spec:
  rules:
  - host: gitlab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitlab-webservice
            port:
              number: 80
  - host: argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
