Vagrant.configure("2") do |config|
    BOX_NAME = "debian/bookworm64" # Debian 12
    VM_MEMORY = 1024
    VM_CPUS = 1
    
    config.vm.define "tdemirS" do |server|
      server.vm.box = BOX_NAME
      server.vm.hostname = "tdemirS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus = VM_CPUS
      end
      server.vm.provision "shell", inline: <<-SHELL
        bash /vagrant/scripts/server.sh
      SHELL
    end
  
    config.vm.define "tdemirSW" do |server_worker|
      server_worker.vm.box = BOX_NAME
      server_worker.vm.hostname = "tdemirSW"
      server_worker.vm.network "private_network", ip: "192.168.56.111"
      server_worker.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus = VM_CPUS
      end
      server_worker.vm.provision "shell", inline: <<-SHELL
        bash /vagrant/scripts/worker.sh
      SHELL
    end
  end
  