Vagrant.configure("2") do |config|
    if Vagrant.has_plugin? "vagrant-vbguest"
      config.vbguest.no_install  = true
    end
  
    BOX_NAME = "debian/bookworm64"
    VM_MEMORY = 8192
    VM_CPUS = 4
    
    config.vm.define "bonus" do |server|
      server.vm.box = BOX_NAME
      server.vm.hostname = "bonus"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus = VM_CPUS
      end
      server.vm.provision "shell", inline: <<-SHELL
        # bash /vagrant/scripts/init.sh
        # bash /vagrant/scripts/gitlab_init.sh
        # bash /vagrant/scripts/is_ready.sh
      SHELL
    end
  end
  